/* WatchTrack v2.7.2 – Serienliste: Als Nächstes | Meine Serien | Gesehen */
(() => {
  let mode='series';
  function watched(item,s,e){const v=item?.seasons?.[s];if(Array.isArray(v))return v.includes(e)||v.includes(String(e));if(v&&typeof v==='object')return !!(v[e]||v[String(e)]);return false;}
  function nextKnownEpisode(item){const meta=item?.seasonMeta||{};for(const s of Object.keys(meta).map(Number).filter(n=>n>0).sort((a,b)=>a-b)){const m=meta[s]||meta[String(s)]||{};const count=Number(m.episode_count||m.episodeCount||m.count||0);for(let e=1;e<=count;e++)if(!watched(item,s,e))return{season:s,episode:e};}return null;}
  function candidate(item){if(!item||item.type!=='tv'||item.status==='completed')return null;const now=new Date();now.setHours(0,0,0,0);const a=item.nextEpisode;if(a?.airDate&&!watched(item,a.season,a.episode)){const d=new Date(a.airDate+'T00:00:00');if(d<=now)return{item,season:a.season,episode:a.episode,rank:0,label:'🆕 Neue Folge verfügbar'};}const n=nextKnownEpisode(item);if(n)return{item,...n,rank:item.status==='watching'?1:2,label:item.status==='watching'?'▶ Weitergucken':'Als Nächstes'};if(a?.airDate&&!watched(item,a.season,a.episode))return{item,season:a.season,episode:a.episode,rank:3,label:`📅 ${dateDE(a.airDate)}`};return null;}
  function nextHtml(){const r=Object.values(state.library||{}).map(candidate).filter(Boolean).sort((a,b)=>a.rank-b.rank||(b.item.updatedAt||0)-(a.item.updatedAt||0));if(!r.length)return '<div class="next-up-empty"><h3>Nichts offen 🎉</h3><p>Aktuell gibt es hier keine nächste Folge.</p></div>';return `<div class="next-up-list">${r.map(x=>`<div class="next-up-row" data-open="tv:${x.item.id}">${x.item.poster_path?`<img src="${IMG+x.item.poster_path}" alt="">`:'<div class="next-up-poster">📺</div>'}<div class="next-up-copy"><strong>${esc(x.item.title)}</strong><span>Staffel ${x.season} · Folge ${x.episode}</span><small>${esc(x.label)}</small></div><button class="primary small" data-next-done="${x.item.id}:${x.season}:${x.episode}">✓ Gesehen</button></div>`).join('')}</div>`;}
  function mount(){const view=document.querySelector('#view-library'),content=document.querySelector('#libraryContent');if(!view||!content)return;const oldFilters=view.querySelector('.library-stats + .segmented');if(oldFilters)oldFilters.style.display=state.libraryType==='tv'?'none':'';if(document.querySelector('#seriesViewTabs'))return;const tabs=document.createElement('div');tabs.id='seriesViewTabs';tabs.className='segmented next-tabs';tabs.innerHTML='<button class="seg" data-next-mode="next">Als Nächstes</button><button class="seg active" data-next-mode="series">Meine Serien</button><button class="seg" data-next-mode="done">Gesehen</button>';content.parentNode.insertBefore(tabs,content);const host=document.createElement('div');host.id='nextUpHost';host.hidden=true;content.parentNode.insertBefore(host,content);}
  function renderMode(){mount();const view=document.querySelector('#view-library'),tabs=document.querySelector('#seriesViewTabs'),host=document.querySelector('#nextUpHost'),content=document.querySelector('#libraryContent');if(!tabs||!host||!content)return;const oldFilters=view.querySelector('.library-stats + .segmented');const isSeries=state.libraryType==='tv';tabs.hidden=!isSeries;if(oldFilters)oldFilters.style.display=isSeries?'none':'';if(!isSeries){host.hidden=true;content.hidden=false;return;}tabs.querySelectorAll('[data-next-mode]').forEach(b=>b.classList.toggle('active',b.dataset.nextMode===mode));if(mode==='next'){host.hidden=false;content.hidden=true;host.innerHTML='<section class="next-up"><div class="next-up-head"><div><h2>Als Nächstes</h2><p>Basierend auf eurem gespeicherten Folgenfortschritt</p></div></div>'+nextHtml()+'</section>';return;}host.hidden=true;content.hidden=false;const all=Object.values(state.library||{}).filter(x=>x.type==='tv').sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));const items=mode==='done'?all.filter(x=>x.status==='completed'):all.filter(x=>x.status!=='completed');content.className='library-list library-single-type';content.innerHTML=items.length?items.map(wt24Row).join(''):empty(mode==='done'?'Noch keine gesehenen Serien':'Keine offenen Serien',mode==='done'?'Fertig gesehene Serien erscheinen hier.':'Neue und laufende Serien erscheinen hier.');}
  const base=window.renderLibrary;window.renderLibrary=function(){const r=base.apply(this,arguments);setTimeout(renderMode,0);return r;};
  document.addEventListener('click',e=>{const tab=e.target.closest('[data-next-mode]');if(tab){mode=tab.dataset.nextMode;renderMode();return;}const b=e.target.closest('[data-next-done]');if(!b)return;e.preventDefault();e.stopPropagation();const [id,s,eNo]=b.dataset.nextDone.split(':').map(Number),item=state.library[keyFor('tv',id)];if(!item)return;item.seasons=item.seasons||{};const cur=item.seasons[s]||item.seasons[String(s)];if(Array.isArray(cur)){if(!cur.includes(eNo))cur.push(eNo);}else{item.seasons[s]=(cur&&typeof cur==='object')?cur:{};item.seasons[s][eNo]=true;}item.status='watching';item.updatedAt=Date.now();saveLibrary();renderLibrary();toast(`S${s} E${eNo} als gesehen markiert`);});
  setTimeout(renderMode,0);
})();