/* WatchTrack Sport – personal favorites, events and reminder preferences */
(()=>{
const STORE='wt_sport_profile_v1';
const seed={favorites:[],events:[],settings:{eventAnnounced:true,eventDay:true,oneHour:true}};
function load(){try{return {...seed,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return structuredClone(seed)}}
let sport=load();
function save(){localStorage.setItem(STORE,JSON.stringify(sport));render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mount(){const old=document.querySelector('#wtSportPlaceholder');if(!old||document.querySelector('#wtSportApp'))return;old.innerHTML='';old.id='wtSportApp';old.classList.add('wt-sport-app');render()}
function render(){const root=document.querySelector('#wtSportApp');if(!root)return;const fav=sport.favorites||[],events=sport.events||[];root.innerHTML=`<div class="sport-hero"><div><span class="sport-kicker">NUR FÜR MICH</span><h2>Mein Sport</h2><p>Favoriten und Erinnerungen bleiben auf diesem Gerät persönlich.</p></div><button id="sportAddBtn" class="primary small">+ Favorit</button></div><div class="sport-tabs"><button class="sport-tab active" data-sport-tab="events">Termine</button><button class="sport-tab" data-sport-tab="favorites">Favoriten <b>${fav.length}</b></button><button class="sport-tab" data-sport-tab="alerts">🔔 Push</button></div><div id="sportPane"></div>`;
root.querySelector('#sportAddBtn').onclick=addFavorite;root.querySelectorAll('.sport-tab').forEach(b=>b.onclick=()=>selectTab(b.dataset.sportTab));selectTab(root.dataset.tab||'events')}
function selectTab(tab){const root=document.querySelector('#wtSportApp');if(!root)return;root.dataset.tab=tab;root.querySelectorAll('.sport-tab').forEach(b=>b.classList.toggle('active',b.dataset.sportTab===tab));const pane=root.querySelector('#sportPane');if(tab==='favorites')renderFavorites(pane);else if(tab==='alerts')renderAlerts(pane);else renderEvents(pane)}
function addFavorite(){const name=prompt('Name des Vereins, Teams, Sportlers oder der Liga/Organisation:');if(!name?.trim())return;const kind=prompt('Art eingeben: Team, Sportler oder Liga','Team')||'Team';sport.favorites.push({id:crypto.randomUUID(),name:name.trim(),kind:kind.trim(),notify:true,createdAt:Date.now()});save();setTimeout(()=>selectTab('favorites'))}
function renderFavorites(p){const a=sport.favorites||[];p.innerHTML=a.length?`<div class="sport-list">${a.map(x=>`<div class="sport-item"><div class="sport-icon">${/liga|organisation/i.test(x.kind)?'🏆':/sportler|kämpfer|fighter/i.test(x.kind)?'🥊':'⚽'}</div><div class="sport-item-main"><b>${esc(x.name)}</b><small>${esc(x.kind)}</small></div><button class="sport-bell ${x.notify?'on':''}" data-bell="${x.id}" aria-label="Benachrichtigungen">🔔</button><button class="sport-remove" data-remove="${x.id}">×</button></div>`).join('')}</div>`:`<div class="sport-empty"><b>Noch keine Sport-Favoriten</b><span>Füge z. B. deinen Verein, einen Kämpfer oder eine komplette Organisation wie OKTAGON hinzu.</span></div>`;p.querySelectorAll('[data-bell]').forEach(b=>b.onclick=()=>{const x=a.find(v=>v.id===b.dataset.bell);if(x){x.notify=!x.notify;save();setTimeout(()=>selectTab('favorites'))}});p.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{sport.favorites=a.filter(x=>x.id!==b.dataset.remove);save();setTimeout(()=>selectTab('favorites'))})}
function renderEvents(p){const e=sport.events||[];p.innerHTML=`<button id="sportEventAdd" class="sport-add-event">＋ Termin hinzufügen</button>${e.length?`<div class="sport-list">${e.sort((a,b)=>a.when.localeCompare(b.when)).map(x=>`<div class="sport-item"><div class="sport-date"><b>${new Date(x.when).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}</b><small>${new Date(x.when).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</small></div><div class="sport-item-main"><b>${esc(x.title)}</b><small>${esc(x.note||'Sportevent')}</small></div><button class="sport-bell ${x.notify?'on':''}" data-eventbell="${x.id}">🔔</button><button class="sport-remove" data-eventremove="${x.id}">×</button></div>`).join('')}</div>`:`<div class="sport-empty"><b>Keine anstehenden Termine</b><span>Hier erscheinen später automatisch die Events deiner Favoriten. Eigene Termine kannst du jetzt schon eintragen.</span></div>`}`;p.querySelector('#sportEventAdd').onclick=addEvent;p.querySelectorAll('[data-eventbell]').forEach(b=>b.onclick=()=>{const x=e.find(v=>v.id===b.dataset.eventbell);if(x){x.notify=!x.notify;save()}});p.querySelectorAll('[data-eventremove]').forEach(b=>b.onclick=()=>{sport.events=e.filter(x=>x.id!==b.dataset.eventremove);save()})}
function addEvent(){const title=prompt('Welches Spiel oder Event?');if(!title?.trim())return;const when=prompt('Datum und Uhrzeit, z. B. 2026-09-20 18:30');if(!when)return;const d=new Date(when.replace(' ','T'));if(Number.isNaN(d.getTime()))return alert('Datum konnte nicht erkannt werden.');sport.events.push({id:crypto.randomUUID(),title:title.trim(),when:d.toISOString(),notify:true,createdAt:Date.now()});save()}
function renderAlerts(p){const s=sport.settings||seed.settings;p.innerHTML=`<div class="sport-alert-card"><h3>Persönliche Sport-Erinnerungen</h3><p>Diese Einstellungen gelten nur für deine Sport-Favoriten auf diesem Gerät.</p>${[['eventAnnounced','Neues Event angekündigt'],['eventDay','Am Tag des Events'],['oneHour','1 Stunde vorher']].map(([k,t])=>`<label class="sport-toggle"><span>${t}</span><input type="checkbox" data-setting="${k}" ${s[k]?'checked':''}></label>`).join('')}<button id="sportPushPermission" class="secondary">Push-Berechtigung prüfen</button><div id="sportPushStatus" class="help-text"></div></div>`;p.querySelectorAll('[data-setting]').forEach(i=>i.onchange=()=>{sport.settings[i.dataset.setting]=i.checked;localStorage.setItem(STORE,JSON.stringify(sport))});p.querySelector('#sportPushPermission').onclick=async()=>{const out=p.querySelector('#sportPushStatus');if(!('Notification'in window)){out.textContent='Push wird von diesem Browser nicht unterstützt.';return}const r=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;out.textContent=r==='granted'?'Push ist auf diesem Gerät erlaubt.':'Push ist auf diesem Gerät noch nicht erlaubt.'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount));else setTimeout(mount);
})();