/* WatchTrack v2.9 – Demnächst aus der eigenen Liste */
(() => {
  const horizon=180;
  const cache=new Map();
  const today=()=>new Date().toISOString().slice(0,10);
  const until=()=>new Date(Date.now()+horizon*86400000).toISOString().slice(0,10);
  function valid(d){return d&&d>=today()&&d<=until();}
  async function eventsFor(item){if(!item||item.manual||!/^\d+$/.test(String(item.id||'')))return[];const k=`${item.type}:${item.id}`;if(cache.has(k))return cache.get(k);let out=[];try{if(item.type==='movie'){const d=await api(`/movie/${item.id}`,{language:'de-DE'});if(valid(d.release_date))out.push({date:d.release_date,type:'movie',item,label:'Filmstart'});}else if(item.type==='tv'){const d=await api(`/tv/${item.id}`,{language:'de-DE'});const n=d.next_episode_to_air;if(n?.air_date&&valid(n.air_date))out.push({date:n.air_date,type:'tv',item,season:n.season_number,episode:n.episode_number,label:`S${n.season_number} E${n.episode_number}`});else{const seasons=(d.seasons||[]).filter(s=>s.season_number>0&&valid(s.air_date));for(const s of seasons.slice(-1))out.push({date:s.air_date,type:'tv',item,season:s.season_number,label:`Staffel ${s.season_number} startet`});}}}catch{}cache.set(k,out);return out;}
  function mount(){const view=document.querySelector('#view-library');if(!view||document.querySelector('#upcomingLibraryBtn'))return;const typeSwitch=document.querySelector('#libraryTypeSwitch');const btn=document.createElement('button');btn.id='upcomingLibraryBtn';btn.className='secondary upcoming-library-btn';btn.textContent='📅 Demnächst';(typeSwitch||view.firstElementChild).insertAdjacentElement('afterend',btn);const host=document.createElement('div');host.id='upcomingLibraryHost';host.hidden=true;btn.insertAdjacentElement('afterend',host);btn.addEventListener('click',()=>show());}
  async function show(){const host=document.querySelector('#upcomingLibraryHost'),content=document.querySelector('#libraryContent'),tabs=document.querySelector('#seriesViewTabs');if(!host)return;const open=host.hidden;if(!open){host.hidden=true;content.hidden=false;if(tabs&&state.libraryType==='tv')tabs.hidden=false;return;}host.hidden=false;content.hidden=true;if(tabs)tabs.hidden=true;host.innerHTML='<div class="empty loading"><span class="spinner"></span><strong>Demnächst</strong><span>Termine aus eurer Liste werden geladen …</span></div>';const all=Object.values(state.library||{}).filter(x=>x.status!=='completed'||x.type==='tv');const chunks=await Promise.all(all.map(eventsFor));const ev=chunks.flat().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,30);host.innerHTML=`<section class="next-up upcoming-library"><div class="next-up-head"><div><h2>Demnächst</h2><p>Nur kommende Termine aus eurer eigenen Liste</p></div></div>${ev.length?`<div class="next-up-list">${ev.map(x=>`<div class="next-up-row" data-open="${x.type}:${x.item.id}">${x.item.poster_path?`<img src="${IMG+x.item.poster_path}" alt="">`:`<div class="next-up-poster">${x.type==='tv'?'📺':'🎬'}</div>`}<div class="next-up-copy"><strong>${esc(x.item.title)}</strong><span>${esc(x.label)}</span><small>📅 ${esc(dateDE(x.date))}</small></div></div>`).join('')}</div>`:empty('Nichts angekündigt','Für eure gespeicherten Titel gibt es in den nächsten 180 Tagen noch keinen bekannten Termin.')}</section>`;}
  const base=window.renderLibrary;window.renderLibrary=function(){const r=base.apply(this,arguments);setTimeout(mount,0);return r;};mount();
})();