/* WatchTrack v3.1 – Abgebrochen, Statistik, Vorlieben */
(()=>{
 const watchedCount=i=>Object.values(i.seasons||{}).reduce((n,v)=>n+(Array.isArray(v)?v.length:Object.values(v||{}).filter(Boolean).length),0);
 function mountStats(){const view=document.querySelector('#view-library');if(!view||document.querySelector('#wtStatsBtn'))return;const b=document.createElement('button');b.id='wtStatsBtn';b.className='secondary';b.textContent='📊 Statistik';const h=document.createElement('div');h.id='wtStatsHost';h.hidden=true;(document.querySelector('#upcomingLibraryBtn')||view.firstElementChild).insertAdjacentElement('afterend',b);b.insertAdjacentElement('afterend',h);b.onclick=()=>{h.hidden=!h.hidden;if(!h.hidden)renderStats(h);};}
 function renderStats(h){const a=Object.values(state.library||{}),movies=a.filter(x=>x.type==='movie'&&x.status==='completed').length,tv=a.filter(x=>x.type==='tv'&&x.status==='completed').length,eps=a.filter(x=>x.type==='tv').reduce((n,x)=>n+watchedCount(x),0),seasons=a.filter(x=>x.type==='tv').reduce((n,x)=>n+Object.values(x.seasons||{}).filter(v=>Array.isArray(v)?v.length:Object.values(v||{}).some(Boolean)).length,0),ab=a.filter(x=>x.status==='dropped').length;h.innerHTML=`<section class="settings-card"><h2>📊 Statistik</h2><div class="library-stats"><div class="stat"><strong>${movies}</strong><span>Filme gesehen</span></div><div class="stat"><strong>${tv}</strong><span>Serien fertig</span></div><div class="stat"><strong>${seasons}</strong><span>Staffeln begonnen</span></div><div class="stat"><strong>${eps}</strong><span>Folgen gesehen</span></div><div class="stat"><strong>${ab}</strong><span>Abgebrochen</span></div></div></section>`;}
 function addDropped(){const d=state.currentDetail;if(!d||d.media_type!=='tv')return;const box=document.querySelector('#detailContent');if(!box||box.querySelector('[data-drop-series]'))return;const i=state.library[keyFor('tv',d.id)];if(!i)return;const btn=document.createElement('button');btn.className='secondary';btn.dataset.dropSeries='1';btn.textContent=i.status==='dropped'?'▶ Wieder aufnehmen':'⛔ Abgebrochen';btn.onclick=()=>{i.status=i.status==='dropped'?'watching':'dropped';i.updatedAt=Date.now();saveLibrary();renderDetail(d);renderLibrary();toast(i.status==='dropped'?'Serie als abgebrochen markiert':'Serie wieder aufgenommen');};(box.querySelector('.detail-actions')||box).appendChild(btn);}
 function prefLabel(p){return p==='love'?'👍👍':p==='like'?'👍':p==='dislike'?'👎':'';}
 function addPreference(){const d=state.currentDetail;if(!d)return;const i=state.library[keyFor(d.media_type,d.id)];const box=document.querySelector('#detailContent');if(!i||!box||box.querySelector('#wtPreference'))return;const wrap=document.createElement('div');wrap.id='wtPreference';wrap.className='settings-card';wrap.innerHTML=`<h3>Wie fandet ihr es?</h3><div class="row gap wrap"><button class="secondary" data-pref="love">👍👍 Richtig gut</button><button class="secondary" data-pref="like">👍 Gut</button><button class="secondary" data-pref="dislike">👎 Nicht meins</button></div><p class="help-text">Beeinflusst eure Vorschläge unter „Für euch“.</p>`;wrap.querySelectorAll('[data-pref]').forEach(b=>{b.classList.toggle('primary',i.preference===b.dataset.pref);b.onclick=()=>{const p=b.dataset.pref;i.preference=i.preference===p?null:p;i.updatedAt=Date.now();saveLibrary();renderDetail(d);renderLibrary();toast(i.preference?`${prefLabel(i.preference)} Vorliebe gespeichert`:'Vorliebe entfernt');};});box.appendChild(wrap);}
 const rd=window.renderDetail;window.renderDetail=function(){const r=rd.apply(this,arguments);setTimeout(()=>{addDropped();addPreference();},0);return r;};
 const rl=window.renderLibrary;window.renderLibrary=function(){const r=rl.apply(this,arguments);setTimeout(()=>{mountStats();document.querySelectorAll('.library-row').forEach(row=>{const key=row.dataset.open;if(!key)return;const i=state.library[key];const target=row.querySelector('.library-copy,.library-info');if(i?.status==='dropped'&&!row.querySelector('.dropped-badge')){const x=document.createElement('span');x.className='badge dropped-badge';x.textContent='⛔ Abgebrochen';target?.appendChild(x);}if(i?.preference&&!row.querySelector('.pref-badge')){const x=document.createElement('span');x.className='badge pref-badge';x.textContent=prefLabel(i.preference);target?.appendChild(x);}});},0);return r;};
 window.wtIsDropped=i=>i?.status==='dropped';mountStats();
})();