const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=900'}});
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const TEAMS=[
{id:'mainz-05',slug:'1-fsv-mainz-05',name:'1. FSV Mainz 05',aliases:['Mainz','Mainz 05','M05'],code:'M05'},
{id:'bayern',slug:'fc-bayern-muenchen',name:'FC Bayern München',aliases:['Bayern','Bayern München','FCB'],code:'FCB'},
{id:'dortmund',slug:'borussia-dortmund',name:'Borussia Dortmund',aliases:['Dortmund','BVB'],code:'BVB'},
{id:'frankfurt',slug:'eintracht-frankfurt',name:'Eintracht Frankfurt',aliases:['Frankfurt','Eintracht','SGE'],code:'SGE'},
{id:'gladbach',slug:'borussia-moenchengladbach',name:'Borussia Mönchengladbach',aliases:['Gladbach','Mönchengladbach','BMG'],code:'BMG'},
{id:'leverkusen',slug:'bayer-04-leverkusen',name:'Bayer 04 Leverkusen',aliases:['Leverkusen','Bayer 04','B04'],code:'B04'},
{id:'schalke',slug:'fc-schalke-04',name:'FC Schalke 04',aliases:['Schalke','Schalke 04','S04'],code:'S04'},
{id:'bremen',slug:'sv-werder-bremen',name:'SV Werder Bremen',aliases:['Bremen','Werder','Werder Bremen','SVW'],code:'SVW'},
{id:'hamburg',slug:'hamburger-sv',name:'Hamburger SV',aliases:['Hamburg','HSV'],code:'HSV'},
{id:'stuttgart',slug:'vfb-stuttgart',name:'VfB Stuttgart',aliases:['Stuttgart','VFB'],code:'VFB'},
{id:'leipzig',slug:'rb-leipzig',name:'RB Leipzig',aliases:['Leipzig','RBL'],code:'RBL'},
{id:'augsburg',slug:'fc-augsburg',name:'FC Augsburg',aliases:['Augsburg','FCA'],code:'FCA'},
{id:'freiburg',slug:'sc-freiburg',name:'Sport-Club Freiburg',aliases:['SC Freiburg','Freiburg','SCF'],code:'SCF'},
{id:'koeln',slug:'1-fc-koeln',name:'1. FC Köln',aliases:['Köln','Koeln','FC Köln','KOE'],code:'KOE'},
{id:'union',slug:'1-fc-union-berlin',name:'1. FC Union Berlin',aliases:['Union','Union Berlin','FCU'],code:'FCU'},
{id:'hoffenheim',slug:'tsg-hoffenheim',name:'TSG Hoffenheim',aliases:['Hoffenheim','TSG'],code:'TSG'},
{id:'elversberg',slug:'sv-elversberg',name:'SV Elversberg',aliases:['Elversberg','ELV'],code:'ELV'},
{id:'paderborn',slug:'sc-paderborn-07',name:'SC Paderborn 07',aliases:['Paderborn','SCP'],code:'SCP'}];
const CODE_NAME=Object.fromEntries(TEAMS.map(t=>[t.code,t.name]));
const OKTAGON=[
{idEvent:'oktagon-94',strEvent:'OKTAGON 94: ECKERLIN VS. KOZMA',strLeague:'OKTAGON MMA',strTimestamp:'2026-09-26T15:00:00+02:00',location:'Deutsche Bank Park, Frankfurt am Main',sourceUrl:'https://oktagonmma.com/de/events/125/',fightcard:['Christian Eckerlin vs. David Kozma','Karlos Vémola vs. Frederic Vosgröne','Max Coga vs. Christian Jungwirth','Jaime Cordero vs. Robo Pukač','Fedor Duric vs. Marc Diakiese','Hugo Vach vs. Deniz Ilbay']},
{idEvent:'oktagon-95',strEvent:'OKTAGON 95: KINCL VS. HUMBURGER',strLeague:'OKTAGON MMA',strTimestamp:'2026-10-17T16:00:00+02:00',location:'Mattoni Arena, Karlovy Vary',sourceUrl:'https://oktagonmma.com/de/events/oktagon-95-karlovy-vary/',fightcard:['Patrik Kincl vs. Dominik Humburger','Karel Škvor vs. Tomasz Narkun','Bartl vs. Manning','Hutyra vs. Fodor']},
{idEvent:'oktagon-96',strEvent:'OKTAGON 96: GOGOLADZE VS. KLINKHAMMER',strLeague:'OKTAGON MMA',strTimestamp:'2026-10-31T17:00:00+01:00',location:'SAP Garden, München',sourceUrl:'https://oktagonmma.com/de/events/oktagon-96-munich/',fightcard:['Amiran Gogoladze vs. Felix Klinkhammer']},
{idEvent:'oktagon-97',strEvent:'OKTAGON 97: SEVERINO VS. HOLZER',strLeague:'OKTAGON MMA',strTimestamp:'2026-11-07T17:00:00+01:00',location:'ZAG Arena, Hannover',sourceUrl:'https://oktagonmma.com/de/events/146/',fightcard:['Igor Severino vs. Max Holzer']},
{idEvent:'oktagon-98',strEvent:'OKTAGON 98: LEGIERSKI VS. BUCHINGER',strLeague:'OKTAGON MMA',strTimestamp:'2026-11-21T18:00:00+01:00',location:'WERK ARENA, Třinec',sourceUrl:'https://oktagonmma.com/de/events/',fightcard:['Fightcard wird von OKTAGON laufend ergänzt']},
{idEvent:'oktagon-99',strEvent:'OKTAGON 99: Dortmund',strLeague:'OKTAGON MMA',strTimestamp:'2026-12-05T18:00:00+01:00',location:'Westfalenhalle, Dortmund',sourceUrl:'https://oktagonmma.com/de/events/',fightcard:['Fightcard wird von OKTAGON laufend ergänzt']},
{idEvent:'oktagon-100',strEvent:'OKTAGON 100: Prag',strLeague:'OKTAGON MMA',strTimestamp:'2026-12-29T18:00:00+01:00',location:'O2 arena, Prag',sourceUrl:'https://oktagonmma.com/de/events/',fightcard:['Fightcard wird von OKTAGON laufend ergänzt']}];
async function text(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 WatchTrack/1.0','accept-language':'de-DE,de;q=0.9'},cf:{cacheTtl:900,cacheEverything:true}});if(!r.ok)throw Object.assign(new Error(`Quelle ${r.status}`),{status:r.status});return r.text()}
function strip(h){return h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#039;|&apos;/g,"'").replace(/\s+/g,' ').trim()}
function scoreTeam(t,n){const vals=[t.name,...t.aliases,t.code].map(norm);let score=0;for(const v of vals){if(v===n)score=Math.max(score,100);else if(v.startsWith(n)||n.startsWith(v))score=Math.max(score,80);else if(v.includes(n)||n.includes(v))score=Math.max(score,60)}return score}
function search(q){const n=norm(q);if(['verein','vereine','bundesliga','fussball','fußball','team','teams'].some(v=>norm(v)===n))return TEAMS.map(t=>({id:t.id,type:'team',provider:'public-bundesliga',name:t.name,shortName:t.aliases[0],sport:'Fußball',country:'Deutschland',league:'Bundesliga',badge:''}));const out=TEAMS.map(t=>({t,score:scoreTeam(t,n)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).map(({t})=>({id:t.id,type:'team',provider:'public-bundesliga',name:t.name,shortName:t.aliases[0],sport:'Fußball',country:'Deutschland',league:'Bundesliga',badge:''}));if(norm('oktagon mma').includes(n)||n.includes('oktagon'))out.push({id:'oktagon',type:'league',provider:'public-oktagon',name:'OKTAGON MMA',sport:'MMA',country:'Europa',badge:''});return out.slice(0,20)}
const MONTH={januar:0,februar:1,maerz:2,märz:2,april:3,mai:4,juni:5,juli:6,august:7,september:8,oktober:9,november:10,dezember:11};
async function bundesligaEvents(team){const clubUrl=`https://www.bundesliga.com/de/bundesliga/spieltag/2026-2027/${team.slug}`,c=strip(await text(clubUrl)),out=[],seen=new Set();const months='Januar|Februar|März|Maerz|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember';const cr=new RegExp(`(?:Montag|Dienstag|Mittwoch|Donnerstag|Freitag|Samstag|Sonntag)\\s+(\\d{1,2})\\.?\\s+(${months})\\s+(?:(\\d{1,2}:\\d{2})\\s+)?(?:Image\\s+)?([A-Z0-9]{2,4})\\s+(?:\\d+\\s+)?([A-Z0-9]{2,4})`,'gi');let m;while((m=cr.exec(c))){if(m[4]!==team.code&&m[5]!==team.code)continue;const mon=MONTH[m[2].toLowerCase()],year=mon<7?2027:2026,tm=m[3]||'12:00',d=new Date(`${year}-${String(mon+1).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}T${tm}:00+02:00`);if(d<Date.now()-86400000)continue;const key=`${d.toISOString()}-${m[4]}-${m[5]}`;if(seen.has(key))continue;seen.add(key);out.push({idEvent:`bundesliga-${team.id}-${key}`,strEvent:`${CODE_NAME[m[4]]||m[4]} – ${CODE_NAME[m[5]]||m[5]}`,strLeague:'Bundesliga',strTimestamp:d.toISOString(),sourceUrl:clubUrl})}return out.slice(0,30)}
export async function onRequestGet({request}){const u=new URL(request.url),action=u.searchParams.get('action')||'',id=u.searchParams.get('id')||'',q=(u.searchParams.get('q')||'').trim(),provider=u.searchParams.get('provider')||'';try{if(action==='status')return json({football:true,combat:true,provider:'public-web'});if(action==='search')return json({results:q.length<2?[]:search(q)});if(action==='league-next'&&(provider==='public-oktagon'||id==='oktagon'))return json({events:OKTAGON.filter(e=>new Date(e.strTimestamp)>Date.now()-86400000)});if(action==='team-next'&&provider==='public-bundesliga'){const team=TEAMS.find(t=>t.id===id);if(!team)return json({error:'Verein nicht gefunden'},404);return json({events:await bundesligaEvents(team)});}return json({error:'Quelle wird noch nicht unterstützt'},400)}catch(e){return json({error:e.message||'Öffentliche Sportquelle nicht erreichbar'},e.status&&e.status<600?e.status:502)}}